const express = require("express")
const route = express.Router()
const auth = require('./auth')
const user = require("./user")
const dashboard = require('./dashboard')
const managementUser = require('./managemenUser')
const landing = require('./landing')
const profile = require('./profile')
const testimoni = require("./testimoni")
const fasilitator = require('./fasilitator')

route.use('/auth', auth)
route.use('/user', user)
route.use('/dashboard', dashboard)
route.use('/management-user', managementUser)
route.use('/landing', landing)
route.use('/profile', profile)
route.use("/testimoni", testimoni)
route.use('/fasilitator', fasilitator)
route.use('/jenis-program', require('./jenisProgram'))
route.use('/jenis-kelas', require('./jenisKelas'))
route.use('/jenis-to', require('./jenisTO'))
route.use('/program', require('./program'))
route.use('/program-utama', require('./programUtama'))
route.use("/video", require('./video'))
route.use('/transaksi', require('./transaksi'))
route.use('/voucher', require('./voucher'))
route.use('/history', require('./history'))
route.use("/tryout", require("./tryout"))
route.use("/kelas", require("./kelasOnline"))

module.exports= route