const { EntitySchema, } = require('typeorm')

module.exports= new EntitySchema({
    name:"Users",
    tableName:'users',
    columns:{
        id:{
            primary:true,
            type:'text'
        },
        name:{
            type:'varchar',
            length:50,
            nullable:true,
            default:""
        },
        email:{
            type:'varchar',
            length:50,
            unique:true,
        },
        password:{
            type:'text',
        },
        no_wa:{
            type:'varchar',
            length:15,
            nullable:true,
            default:""
        },
        pin:{
            type:'varchar',
            length:6,
            nullable:true,
            default:""
        },
        username:{
            type:'varchar',
            length:20,
            nullable:true,
            default:""
        },
        tingkat_pend:{
            type:'varchar',
            length:10,
            nullable:true,
            default:""
        },
        provinsi:{
            type:'varchar',
            length:30,
            nullable:true,
            default:""
        },
        kota_kab:{
            type:'varchar',
            length:30,
            nullable:true,
            default:""
        },
        referal:{
            type:'varchar',
            length:25,
            nullable:true
        },
        created_at:{
            type:"timestamp",
            nullable:true,
            default: () => "CURRENT_TIMESTAMP"
        },
        updated_at:{
            type:"timestamp",
            default: () => "CURRENT_TIMESTAMP",
            onUpdate: () => "CURRENT_TIMESTAMP",
            nullable:true
        },
        is_active:{
            type:'boolean',
            default:false
        },
        is_deleted:{
            type:'boolean',
            default:false
        },
        role:{
            type:"varchar",
            default:"users"
        },
        instagram:{
            type:"varchar",
            length:50,
            nullable:true,
            default:""
        },
        expires_at:{
            type:'timestamptz',
            nullable:true
        },
        image:{
            type:'text',
            nullable:true,
            default:""
        }
    }
})